syn on
set ts=4 " tabstop
set sw=4 " shiftwidth
set ai   " autoindent
set si   " smart indent
set sm	 " show matches
"set nu   " show lines number

set title " xterm title
set mouse=a " mouse support is nice

" perl quote hashes
nmap <silent> "" :let tmp=@/<CR>:s/{\([_a-z0-9]\+\)}/{'\1'}/egi<CR>:let @/=tmp<CR>

" toggles search higlight with ^T
nmap <silent><C-t> :set hls!<CR>

" emacs style (or not)
nmap <C-x><C-x> :update<CR>
imap <C-x><C-x> <C-o>:update<CR>
imap <C-a> <Home>
imap <C-e> <End>

" Max resize
nmap <silent><C-W>* :resize<CR>:vertical resize<CR>
nmap <silent><C-W>m :resize<CR>:vertical resize<CR>

" format xml with tidy
nmap tx :set nohls<CR>:%s/\n//e<CR>:%!tidy -i -xml -q -w 0<CR>:set syntax=xml<CR>

" smart edit
vmap " <Esc>`<i"<Esc>`>a"<Esc>l
vmap ' <Esc>`<i'<Esc>`>a'<Esc>l
vmap ( <Esc>`<i(<Esc>`>a)<Esc>l
vmap [ <Esc>`<i[<Esc>`>a]<Esc>l
vmap { <Esc>`<i{<Esc>`>a}<Esc>l

let g:_switchCLines = [ "ctermbg=black", "ctermbg=white", "" ]
let g:_switchCLine=0
function SwitchCLine()
    hi clear CursorLine
    
    let ev = g:_switchCLines[g:_switchCLine]
    if empty(ev)
        set nocursorline
    else
        execute ":hi CursorLine " . ev
        set cursorline
    endif

    if g:_switchCLine + 1 >= len(g:_switchCLines)
        let g:_switchCLine = 0
    else
        let g:_switchCLine = g:_switchCLine + 1
    endif
endfunction
call SwitchCLine()
nmap <F2> :call SwitchCLine()<cr>

function RenderRST()
	write
	let tmpfile = tempname()
	silent execute "!rst2html \"%\" > " . tmpfile . " && x-www-browser " . tmpfile . " >/dev/null"
	redraw!
endfunction

" pour git, plus ou moins
au CursorHold * checktime
set autoread

" Only hilight line in active window
au WinEnter * set cursorline
au WinLeave * set nocursorline

" better tab completion
set wildmode=longest,list,full
set wildmenu

" auto set paste !
if &term == "xterm"
    "let &t_ti = &t_ti . "\e[?2004h"
    "let &t_te = "\e[?2004l" . &t_te
    function XTermPasteBegin(ret)
        set pastetoggle=<Esc>[201~
        set paste
        return a:ret
    endfunction
    "map <expr> <Esc>[200~ XTermPasteBegin("i")
    "imap <expr> <Esc>[200~ XTermPasteBegin("")
endif


nnoremap <silent> <F3> :TlistToggle<CR>
let Tlist_Exit_OnlyWindow = 1
let Tlist_Show_One_File = 1
let Tlist_Enable_Fold_Column = 0
let Tlist_Process_File_Always = 1

if filereadable("/usr/local/bin/ctags")
    let Tlist_Ctags_Cmd="/usr/local/bin/ctags"
endif

" statusline with tags
set laststatus=2
set statusline=%<%f\ %h%m%r%=%([%{Tlist_Get_Tagname_By_Line()}]%)%14.(%l,%c%V%)

let g:netrw_list_hide="\.py[co]$,\..*\.swp$"
let g:netrw_liststyle=3
" set off on Debian, probably for a good reason
set modeline
